CH-15181 Add optional `affiliateId` header to checkout & basket requests
EncoreLabs/js-sdk pull request #30
Opened 2020-10-16 08:16 UTC by MikePolyakovsky

2020-10-16 10:07 UTC, PaulRumyantsevItr requested changes
We should also mention all available parameters in the documentation (README file)

2020-10-16 10:07 UTC, PaulRumyantsevItr commented on src/basket-service/services/__tests__/api-provider.spec.ts
> +    ...{affiliateId: 'encoretickets'},
Spaces missing inside brackets
`...{ affiliateId: 'encoretickets' },`

2020-10-16 10:07 UTC, PaulRumyantsevItr commented on src/checkout-service/services/__tests__/api-provider.spec.ts
> +    ...{affiliateId: 'encoretickets'},
Same as above

2020-10-16 14:45 UTC, MikePolyakovsky commented
> We should also mention all available parameters in the documentation (README file)

fixed

2020-10-16 14:45 UTC, MikePolyakovsky commented on src/basket-service/services/__tests__/api-provider.spec.ts
> +    ...{affiliateId: 'encoretickets'},
fixed

2020-10-16 14:45 UTC, MikePolyakovsky commented on src/checkout-service/services/__tests__/api-provider.spec.ts
> +    ...{affiliateId: 'encoretickets'},
fixed

2020-10-16 14:48 UTC, PaulRumyantsevItr commented
Please, update the version in package.json and package-lock.json

2020-10-16 14:51 UTC, MikePolyakovsky commented
> We should also mention all available parameters in the documentation (README file)

fixed (1.13.0)

2020-10-16 14:53 UTC, PaulRumyantsevItr approved these changes

2020-10-21 17:17 UTC, dpiletski commented
Attaching to the cloubhouse story [15181]

2020-11-05 07:04 UTC, merged